### ISSUE TITLE
Speed up flight planning

### ISSUE THREAD

**Issue by JuliaWindmiller1987** [orcestra-campaign/book#356]
When using the most recent version of the markdown file for flight planning, I always use restart kernel to make sure everything is updated but then it reloads the IFS data which makes it very slow. I know I could just comment it out or not do the restart kernel thing but maybe anyone has a smarter idea of how to e.g. cache stuff? That would be amazing.

**Comment by d70-t** [comment]
This should be relatively easy using [fsspec's filecache](https://filesystem-spec.readthedocs.io/en/latest/features.html#caching-files-locally). For the filecache, a user would have to provide a local caching directory, but in turn, access to files through filecache would be cached and persisted across python sessions.

Implementation-wise, I'd suggest a function in pyorcestra, which wraps an intake catalog entry, and returns a new entry, which uses `filecache`. For configuration, I'd suggest that we allow a file in `~/.config/orcestra`, which points to an appropriate local cache directory. If the configuration file doesn't exist, I'd return the catalog entry as-is (i.e. without caching).

The useage may look like:
```
from orcestra import cached
ds = cached(cat.HIFS(date)).to_dask()
```

I probably can't implement this in the next few days, so if there's someone else volunteering, please go for it!

**Comment by lkluft** [comment]
I think we can make this work without any additional code. We could simply set the `simplecache::` prefix in the HIFS catalog entry. In my opinion, this should never be a problem for users.

This would automatically result in caching **within** running python sessions. Unfortunately, each Python process has its own cache by default, so a restart of the kernel would re-read the data. However, by using the following configuration
```json
~/.config/fsspec/conf.json 
{
  "simplecache": {
    "cache_storage": "/tmp/intake-cache/"
  }
}
```
users can create a cache that doesn't contain any python process id information and, at least in my tests, is persistent across kernel restarts. And since it's under `/tmp', the system is still able to remove data if necessary.

**Comment by d70-t** [comment]
I like that option as well.
I've just merged the `simplecache` addition to the catalog, so the change should now be functional. I'd keep this issue open until we've added some documentation about this feature to the book.

**Comment by lkluft** [comment]
The configuration of the local cache is now available in our [technical FAQ](https://orcestra-campaign.org/faq.html#how-to-speedup-execution-of-code-cells).

For me, this speeds up the execution of code cells significantly, so I will close this issue. Feel free to reopen if the issue persists.
